### ISSUE TITLE
Flag Combinations to Test

### ISSUE THREAD

**Issue by pid1** [pid1/test-sec-flags#1]
We should decide which flag combinations we want to include in our testing. Ideas already raised have included -fPIE by itself, -fstack-protector-strong by itself, and these in combination. Please add these to FLAGS.rst, and use this issue for discussion.

**Comment by HalosGhost** [comment]
We could, if we're okay with the test suite taking a long time, script it to just try every possible combination of all the flags put in the list, hehe.

**Comment by rgacogne** [comment]
Ideally I'd like to see:
- current Arch's flags, ie -fstack-protector-strong and partial relro
-  -fstack-protector-strong and partial relro + PIE
- -fstack-protector-strong and PIE + full RELRO
- -fstack-protector-strong and PIE + full RELRO + no-plt

**Comment by anthraxx** [comment]
please also add '-fstack-check' to the testing flags.
- current Arch's flags, ie -fstack-protector-strong and partial relro
- current Arch's flags, ie -fstack-protector-strong and partial relro + stack-check
- -fstack-protector-strong and partial relro + PIE
- -fstack-protector-strong and partial relro + PIE + stack-check
- -fstack-protector-strong and PIE + full RELRO
- -fstack-protector-strong and PIE + full RELRO + stack-check
- -fstack-protector-strong and PIE + full RELRO + no-plt
- -fstack-protector-strong and PIE + full RELRO + no-plt + stack-check

**Comment by pid1** [comment]
Added to FLAGS.rst

**Comment by pid1** [comment]
All of the flags suggested have been implemented. Please go through and verify that the flags are correct for each option. Adding new tests, if we desire them, should be trivial.

**Comment by pid1** [comment]
Closing, since we have all the flags that came up in discussion. Feel free to re-open if the current selection is insufficient.
