### ISSUE TITLE
test_ffmpeg seems to stuck on compile (?)

### ISSUE THREAD

**Issue by inglor** [pid1/test-sec-flags#10]
The test_ffmpeg seems to stuck on compilation. CPU shows 100% and processes (8) are RUNNING.

``` log
License: GPL version 3 or later  
Creating config.mak, config.h, and doc/config.texi...  
config.h is unchanged  
config.asm is unchanged  
libavutil/avconfig.h is unchanged  
CC  libavdevice/alsa.o  
CC  libavdevice/alldevices.o  
CC  libavdevice/alsa_dec.o  
CC  libavdevice/alsa_enc.o  
CC  libavdevice/avdevice.o  
CC  libavdevice/dv1394.o  
CC  libavdevice/fbdev_common.o  
CC  libavdevice/fbdev_dec.o
```

See top screenshot:
![top](https://cloud.githubusercontent.com/assets/301857/15551892/f493ca20-22af-11e6-8886-49c2fadc9561.png)

**Comment by pid1** [comment]
Let me see if I can reproduce.

**Comment by pid1** [comment]
Worked for me with a fresh download and build. What were the circumstances in which this occurred? Did you install the necessary ffmpeg deps and makedeps?

**Comment by inglor** [comment]
For dependencies I just compiled https://aur.archlinux.org/packages/ffmpeg-full/ so I assume I have them. How can I clear the build and try again?

My process was:
- clone repo
- setup
- test xz
- test unix
- test ffmpeg

**Comment by pid1** [comment]
See the README, you need the deps and makedeps for [ffmpeg.](https://git.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/ffmpeg)

**Comment by inglor** [comment]
I have the deps and makedeps for ffmpeg.

**Comment by anthraxx** [comment]
this happens if you have other gcc wrappers installed like colorgcc or ccache. please remove those from your path when executing those tests

**Comment by inglor** [comment]
@anthraxx indeed I have `ccache` - I will try without. Thanks

**Comment by klusark** [comment]
I'm having this issue as well. Could you add the conflicting software to the readme?

**Comment by anthraxx** [comment]
@klusark We can add a hint. there may be an arbitrary amount of things that wrap gcc

**Comment by klusark** [comment]
@anthraxx Looks good! Thanks for fixing it.
