### ISSUE TITLE
ffmpeg tests are broken

### ISSUE THREAD

**Issue by pid1** [pid1/test-sec-flags#5]
The flags for ffmpeg are being set at all.

**Comment by pid1** [comment]
@anthraxx Does #7 fix this as well?

**Comment by anthraxx** [comment]
not yet, next PR coming soon

**Comment by anthraxx** [comment]
fixed by https://github.com/pid1/test-sec-flags/pull/8

**Comment by pid1** [comment]
Merged #8.
