### ISSUE TITLE
measure the overhead of UBSan bounds checking

### ISSUE THREAD

**Issue by thestinger** [pid1/test-sec-flags#9]
It would be neat to measure the overhead of `-fsanitize=bounds,object-size -fsanitize-undefined-trap-on-error`. It's going to be way too expensive to enable on Arch, but it's useful information nonetheless. There are some other hardening-friendly UBSan subsets that might also be worth measuring.

**Comment by pid1** [comment]
Sure, sounds fine to me. Add whatever flags we should test here and I'll integrate them where appropriate.

**Comment by pid1** [comment]
Closing, added to https://github.com/pid1/test-sec-flags/wiki/Feature-Requests
